// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/v1/auth/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateInput struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateInput) Reset()         { *m = AuthenticateInput{} }
func (m *AuthenticateInput) String() string { return proto.CompactTextString(m) }
func (*AuthenticateInput) ProtoMessage()    {}
func (*AuthenticateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7480fa04fbd8e1b6, []int{0}
}

func (m *AuthenticateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateInput.Unmarshal(m, b)
}
func (m *AuthenticateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateInput.Marshal(b, m, deterministic)
}
func (m *AuthenticateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateInput.Merge(m, src)
}
func (m *AuthenticateInput) XXX_Size() int {
	return xxx_messageInfo_AuthenticateInput.Size(m)
}
func (m *AuthenticateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateInput.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateInput proto.InternalMessageInfo

func (m *AuthenticateInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateInput) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AuthenticateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7480fa04fbd8e1b6, []int{1}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshInput struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshInput) Reset()         { *m = RefreshInput{} }
func (m *RefreshInput) String() string { return proto.CompactTextString(m) }
func (*RefreshInput) ProtoMessage()    {}
func (*RefreshInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_7480fa04fbd8e1b6, []int{2}
}

func (m *RefreshInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshInput.Unmarshal(m, b)
}
func (m *RefreshInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshInput.Marshal(b, m, deterministic)
}
func (m *RefreshInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshInput.Merge(m, src)
}
func (m *RefreshInput) XXX_Size() int {
	return xxx_messageInfo_RefreshInput.Size(m)
}
func (m *RefreshInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshInput.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshInput proto.InternalMessageInfo

func (m *RefreshInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7480fa04fbd8e1b6, []int{3}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateInput)(nil), "auth.AuthenticateInput")
	proto.RegisterType((*AuthenticateResponse)(nil), "auth.AuthenticateResponse")
	proto.RegisterType((*RefreshInput)(nil), "auth.RefreshInput")
	proto.RegisterType((*RefreshResponse)(nil), "auth.RefreshResponse")
}

func init() {
	proto.RegisterFile("grpc/v1/auth/auth.proto", fileDescriptor_7480fa04fbd8e1b6)
}

var fileDescriptor_7480fa04fbd8e1b6 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x33, 0xd4, 0x4f, 0x2c, 0x2d, 0xc9, 0x00, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0x2c, 0x20, 0xb6, 0x92, 0x37, 0x97, 0xa0, 0x63, 0x69, 0x49, 0x46, 0x6a, 0x5e, 0x49, 0x66,
	0x72, 0x62, 0x49, 0xaa, 0x67, 0x5e, 0x41, 0x69, 0x89, 0x90, 0x14, 0x17, 0x47, 0x41, 0x62, 0x71,
	0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x0f, 0x92, 0x2b,
	0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x82, 0xc8, 0xc1, 0xf8, 0x4a, 0x3a, 0x5c,
	0x22, 0xc8, 0x86, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x96,
	0xe4, 0x67, 0xa7, 0xe6, 0x41, 0x0d, 0x83, 0x70, 0x94, 0x54, 0xb8, 0x78, 0x82, 0x52, 0xd3, 0x8a,
	0x52, 0x8b, 0x33, 0x20, 0xb6, 0x62, 0x57, 0xa5, 0xce, 0xc5, 0x0f, 0x55, 0x85, 0xdf, 0x38, 0xa3,
	0x66, 0x46, 0x2e, 0xa6, 0x32, 0x43, 0x21, 0x57, 0x2e, 0x1e, 0x64, 0x37, 0x08, 0x89, 0xeb, 0x81,
	0xfd, 0x8c, 0xe1, 0x49, 0x29, 0x29, 0x4c, 0x09, 0x98, 0x0d, 0x4a, 0x0c, 0x42, 0x66, 0x5c, 0xec,
	0x50, 0x6b, 0x85, 0x84, 0x20, 0x0a, 0x91, 0xdd, 0x2a, 0x25, 0x8a, 0x22, 0x86, 0xd0, 0x97, 0xc4,
	0x06, 0x0e, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x5c, 0x88, 0x82, 0x77, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// V1Client is the client API for V1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type V1Client interface {
	Authenticate(ctx context.Context, in *AuthenticateInput, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	Refresh(ctx context.Context, in *RefreshInput, opts ...grpc.CallOption) (*RefreshResponse, error)
}

type v1Client struct {
	cc grpc.ClientConnInterface
}

func NewV1Client(cc grpc.ClientConnInterface) V1Client {
	return &v1Client{cc}
}

func (c *v1Client) Authenticate(ctx context.Context, in *AuthenticateInput, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/auth.v1/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1Client) Refresh(ctx context.Context, in *RefreshInput, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, "/auth.v1/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V1Server is the server API for V1 service.
type V1Server interface {
	Authenticate(context.Context, *AuthenticateInput) (*AuthenticateResponse, error)
	Refresh(context.Context, *RefreshInput) (*RefreshResponse, error)
}

// UnimplementedV1Server can be embedded to have forward compatible implementations.
type UnimplementedV1Server struct {
}

func (*UnimplementedV1Server) Authenticate(ctx context.Context, req *AuthenticateInput) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedV1Server) Refresh(ctx context.Context, req *RefreshInput) (*RefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}

func RegisterV1Server(s *grpc.Server, srv V1Server) {
	s.RegisterService(&_V1_serviceDesc, srv)
}

func _V1_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.v1/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).Authenticate(ctx, req.(*AuthenticateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.v1/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).Refresh(ctx, req.(*RefreshInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _V1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1",
	HandlerType: (*V1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _V1_Authenticate_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _V1_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/v1/auth/auth.proto",
}
