// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baking.proto

package baking

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Block                string   `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	SignedOperation      string   `protobuf:"bytes,2,opt,name=SignedOperation,proto3" json:"SignedOperation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3387353544f28f, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *Block) GetSignedOperation() string {
	if m != nil {
		return m.SignedOperation
	}
	return ""
}

type BlockResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3387353544f28f, []int{1}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BlockResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type BakingStream struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BakingStream) Reset()         { *m = BakingStream{} }
func (m *BakingStream) String() string { return proto.CompactTextString(m) }
func (*BakingStream) ProtoMessage()    {}
func (*BakingStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3387353544f28f, []int{2}
}

func (m *BakingStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BakingStream.Unmarshal(m, b)
}
func (m *BakingStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BakingStream.Marshal(b, m, deterministic)
}
func (m *BakingStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BakingStream.Merge(m, src)
}
func (m *BakingStream) XXX_Size() int {
	return xxx_messageInfo_BakingStream.Size(m)
}
func (m *BakingStream) XXX_DiscardUnknown() {
	xxx_messageInfo_BakingStream.DiscardUnknown(m)
}

var xxx_messageInfo_BakingStream proto.InternalMessageInfo

type Subscribe struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d3387353544f28f, []int{3}
}

func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (m *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(m, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "baking.Block")
	proto.RegisterType((*BlockResponse)(nil), "baking.BlockResponse")
	proto.RegisterType((*BakingStream)(nil), "baking.BakingStream")
	proto.RegisterType((*Subscribe)(nil), "baking.Subscribe")
}

func init() {
	proto.RegisterFile("baking.proto", fileDescriptor_3d3387353544f28f)
}

var fileDescriptor_3d3387353544f28f = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4f, 0x84, 0x30,
	0x10, 0xc5, 0x97, 0x75, 0x5d, 0xdd, 0xc9, 0xae, 0x7f, 0x26, 0x98, 0x10, 0x2e, 0x9a, 0x9e, 0x38,
	0x11, 0xff, 0x9c, 0x8c, 0x37, 0x2e, 0x1e, 0x4d, 0xe0, 0x13, 0xb4, 0x65, 0x42, 0x1a, 0xb4, 0x25,
	0x2d, 0xf5, 0xf3, 0x1b, 0x4a, 0x21, 0xea, 0xed, 0xbd, 0xe9, 0xcc, 0xbc, 0x5f, 0x07, 0x8e, 0x82,
	0xf7, 0x4a, 0x77, 0xe5, 0x60, 0xcd, 0x68, 0x70, 0x3f, 0x3b, 0xf6, 0x0e, 0xe7, 0xd5, 0xa7, 0x91,
	0x3d, 0xa6, 0x51, 0x64, 0xc9, 0x43, 0x52, 0x1c, 0xea, 0x58, 0x2d, 0xe0, 0xba, 0x51, 0x9d, 0xa6,
	0xf6, 0x63, 0x20, 0xcb, 0x47, 0x65, 0x74, 0xb6, 0x0d, 0xef, 0xff, 0xcb, 0xec, 0x0d, 0x4e, 0x61,
	0xa4, 0x26, 0x37, 0x18, 0xed, 0x08, 0x33, 0xb8, 0x70, 0x5e, 0x4a, 0x72, 0x2e, 0xac, 0xbc, 0xac,
	0x17, 0x8b, 0x37, 0x70, 0x46, 0xd6, 0xc6, 0x45, 0x93, 0x64, 0x57, 0x70, 0xac, 0x02, 0x4f, 0x33,
	0x5a, 0xe2, 0x5f, 0xec, 0x1e, 0x0e, 0x8d, 0x17, 0x4e, 0x5a, 0x25, 0x08, 0x11, 0x76, 0xde, 0xab,
	0x36, 0x82, 0x05, 0xfd, 0x6c, 0x60, 0xfb, 0xfd, 0x84, 0x25, 0xec, 0x2a, 0xde, 0x13, 0x9e, 0xca,
	0xf8, 0xb7, 0x40, 0x90, 0xdf, 0xfd, 0xb1, 0x0b, 0x10, 0xdb, 0xe0, 0x2b, 0xc0, 0xd4, 0x3f, 0x87,
	0xe0, 0xed, 0xd2, 0xb6, 0x46, 0xe5, 0xe9, 0x3a, 0xf9, 0x9b, 0x66, 0xf3, 0x98, 0x88, 0x7d, 0x38,
	0xdb, 0xcb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x14, 0x99, 0xcc, 0x46, 0x01, 0x00, 0x00,
}
